'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { account, listOrders, updateOrderStatus } from '@/src/appwrite';
import { money, type OrderItem, type OrderStatus, type StoreOrder, waLink } from '@/src/data';
import { ArrowLeft, ArrowRight, ExternalLink, MessageCircle, PackageCheck, RefreshCw, Search, ShoppingBag, X } from 'lucide-react';
const stages:OrderStatus[]=['New','Confirmed','Processing','Ready','Completed'];
function parseItems(text:string):OrderItem[]{try{const parsed=JSON.parse(text||'[]');return Array.isArray(parsed)?parsed:[];}catch{return[];}}
function niceDate(value?:string){if(!value)return'—';const date=new Date(value);return Number.isNaN(date.getTime())?'—':date.toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'});}
export default function OrdersDashboard(){const router=useRouter();const [orders,setOrders]=useState<StoreOrder[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [filter,setFilter]=useState('All');const [search,setSearch]=useState('');const [selected,setSelected]=useState<StoreOrder|null>(null);const [updating,setUpdating]=useState('');
 const refresh=()=>{setLoading(true);setError('');listOrders().then(setOrders).catch(err=>setError(err instanceof Error?err.message:'Could not load orders. Check the Orders table and its permissions.')).finally(()=>setLoading(false));};
 useEffect(()=>{account.get().then(()=>refresh()).catch(()=>router.replace('/admin'));},[router]);
 const filtered=useMemo(()=>orders.filter(order=>(filter==='All'||order.status===filter)&&(!search||`${order.orderNumber} ${order.customerName} ${order.customerPhone} ${order.deliveryCity}`.toLowerCase().includes(search.toLowerCase()))),[orders,filter,search]);
 const today=orders.filter(o=>o.$createdAt&&new Date(o.$createdAt).toDateString()===new Date().toDateString()).length;const pending=orders.filter(o=>o.status==='New').length;const revenue=orders.reduce((n,o)=>n+(Number(o.total)||0),0);
 const changeStatus=async(order:StoreOrder,status:OrderStatus)=>{if(!order.$id)return;setUpdating(order.$id);setError('');try{const updated=await updateOrderStatus(order.$id,status);setOrders(v=>v.map(item=>item.$id===order.$id?updated:item));setSelected(updated);}catch(err){setError(err instanceof Error?err.message:'Could not update order status. Confirm admin Update permission on the table.');}finally{setUpdating('');}};
 const advance=(order:StoreOrder)=>{const index=stages.indexOf(order.status);if(index<stages.length-1)void changeStatus(order,stages[index+1]);};
 return <main className="min-h-screen" style={{background:'var(--paper)'}}><header className="border-b border-[var(--line)] bg-[var(--white)]"><div className="shell flex min-h-[76px] items-center justify-between gap-3"><Link href="/admin" className="inline-flex items-center gap-2 text-sm text-[var(--muted)]"><ArrowLeft size={16}/> Dashboard</Link><div className="flex items-center gap-2"><Link href={process.env.NEXT_PUBLIC_PUBLIC_SITE_URL||'https://maison-prisca-customer.netlify.app'} target="_blank" className="btn btn-line !px-3 !py-2 text-xs">Preview store <ExternalLink size={13}/></Link><button onClick={refresh} className="rounded-full border border-[var(--line)] p-2" aria-label="Refresh orders"><RefreshCw size={16}/></button></div></div></header>
 <div className="shell py-8 md:py-12"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Order management</p><h1 className="serif mt-2 text-5xl">Orders</h1><p className="mt-2 max-w-xl text-sm text-[var(--muted)]">Review customer details, follow up on WhatsApp and move each order through fulfilment.</p></div><span className="rounded-full border border-[var(--line)] bg-[var(--white)] px-3 py-2 text-xs">{orders.length} loaded</span></div>
 <div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Today',String(today)],['New orders',String(pending)],['All orders',String(orders.length)],['Order value',money(revenue)]].map(([label,value])=><div key={label} className="order-metric"><span className="label">{label}</span><strong className="serif mt-2 block text-3xl">{value}</strong></div>)}</div>
 <div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-y border-[var(--line)] py-3"><div className="flex gap-1 overflow-x-auto">{['All',...stages].map(status=><button key={status} onClick={()=>setFilter(status)} className={`whitespace-nowrap px-3 py-2 text-xs font-semibold ${filter===status?'border-b-2 border-[var(--rose)] text-[var(--rose-deep)]':'text-[var(--muted)]'}`}>{status}</button>)}</div><label className="relative block w-full sm:max-w-xs"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--muted)]" size={16}/><input className="input pl-9" placeholder="Search orders or customer" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
 {error&&<div className="mt-5 border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><strong>Orders could not be loaded.</strong> {error}<p className="mt-2 text-xs">Confirm the Orders table ID, expected attributes, and permissions. Customers need Create; the signed-in admin needs Read and Update.</p></div>}
 {loading?<div className="py-16 text-center text-sm text-[var(--muted)]">Loading orders…</div>:filtered.length?<div className="mt-5 grid gap-3">{filtered.map(order=>{const items=parseItems(order.items);const next=stages[stages.indexOf(order.status)+1];return <article key={order.$id||order.orderNumber} className="order-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><strong className="serif text-2xl">#{order.orderNumber}</strong><span className={`order-status status-${order.status.toLowerCase()}`}>{order.status}</span>{order.ref&&<span className="rounded-full bg-[var(--blush)] px-2 py-1 text-[10px]">ref: {order.ref}</span>}</div><p className="mt-1 text-sm text-[var(--muted)]">{order.customerName} · {niceDate(order.$createdAt)}</p></div><div className="text-right"><strong className="text-lg">{money(Number(order.total)||0)}</strong><p className="text-xs text-[var(--muted)]">{items.reduce((n,i)=>n+(Number(i.quantity)||0),0)} items</p></div></div><div className="mt-4 grid gap-2 border-y border-[var(--line)] py-3 text-sm sm:grid-cols-3"><p><span className="text-[var(--muted)]">Phone</span><strong className="block">{order.customerPhone}</strong></p><p><span className="text-[var(--muted)]">Delivery</span><strong className="block">{order.deliveryCity}, {order.deliveryState}</strong></p><p><span className="text-[var(--muted)]">Items</span><strong className="block truncate">{items.map(i=>i.name).join(', ')||'Order details'}</strong></p></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>setSelected(order)} className="btn btn-line !px-3 !py-2 text-xs">View order</button><a href={waLink(order.customerPhone,`Hello ${order.customerName}, this is Maison Prisca Atelier following up on order ${order.orderNumber}.`)} target="_blank" rel="noreferrer" className="btn btn-line !px-3 !py-2 text-xs"><MessageCircle size={14}/> WhatsApp</a>{next&&<button disabled={Boolean(updating)} onClick={()=>advance(order)} className="btn btn-dark !px-3 !py-2 text-xs">{updating===order.$id?'Saving…':<>Mark {next.toLowerCase()} <ArrowRight size={13}/></>}</button>}</div></article>;})}</div>:<div className="mt-8 border border-dashed border-[var(--line)] bg-[var(--white)] p-12 text-center"><span className="mx-auto grid size-12 place-items-center rounded-full bg-[var(--blush)]"><ShoppingBag size={21}/></span><p className="serif mt-4 text-2xl">{orders.length?'No orders in this view':'No orders yet'}</p><p className="mt-2 text-sm text-[var(--muted)]">New customer checkouts will appear here once saved to the Orders table.</p></div>}
 </div>{selected&&<div className="fixed inset-0 z-50 overflow-y-auto bg-[var(--dusk)]/70 p-3 sm:p-6"><section className="mx-auto my-5 max-w-2xl bg-[var(--white)] p-5 sm:p-7"><header className="flex items-start justify-between gap-4"><div><p className="label">Order details</p><h2 className="serif mt-1 text-3xl">#{selected.orderNumber}</h2></div><button onClick={()=>setSelected(null)} className="rounded-full border border-[var(--line)] p-2" aria-label="Close"><X size={18}/></button></header><div className="mt-5 grid gap-3 border-y border-[var(--line)] py-4 sm:grid-cols-2"><p><span className="label">Customer</span><strong className="block">{selected.customerName}</strong></p><p><span className="label">Phone</span><strong className="block">{selected.customerPhone}</strong></p>{selected.customerEmail&&<p><span className="label">Email</span><strong className="block">{selected.customerEmail}</strong></p>}<p><span className="label">Delivery</span><strong className="block">{selected.deliveryAddress}, {selected.deliveryCity}, {selected.deliveryState}</strong></p>{selected.deliveryNote&&<p className="sm:col-span-2"><span className="label">Delivery note</span><span className="block">{selected.deliveryNote}</span></p>}</div><div className="mt-5"><p className="label">Order items</p>{parseItems(selected.items).map((item,index)=><div key={`${item.productId}-${index}`} className="flex justify-between gap-3 border-b border-[var(--line)] py-3 text-sm"><span>{item.name} · size {item.size} × {item.quantity}</span><strong>{money(item.price*item.quantity)}</strong></div>)}<div className="flex justify-between pt-4"><strong>Total</strong><strong>{money(Number(selected.total)||0)}</strong></div></div><div className="mt-6 flex flex-wrap gap-2"><span className="order-status status-new">{selected.status}</span>{stages[stages.indexOf(selected.status)+1]&&<button disabled={Boolean(updating)} onClick={()=>advance(selected)} className="btn btn-dark !px-3 !py-2 text-xs"><PackageCheck size={14}/> Mark {stages[stages.indexOf(selected.status)+1].toLowerCase()}</button>}</div></section></div>}</main>;
}
